services:
  server_analysis:
    container_name: serverAnalysis
    build:
      context: ./server
      dockerfile: DockerfileDevServer
    env_file:
      - ./server/.development.env
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - "5050:5050"
      - "9229:9229"
    depends_on:
      postgres_analysis:
        condition: service_healthy
      python_pdf_parser:
        condition: service_healthy

  postgres_analysis:
    container_name: postgresAnalysis
    image: postgres:18
    env_file:
      - ./.postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  client_analysis:
    container_name: clientAnalysis
    build:
      context: ./client
      dockerfile: DockerfileDevClient
    env_file:
      - ./client/.dev.env
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  python_pdf_parser:
    container_name: pythonPDFParser
    build:
      context: ./python-microservice
      dockerfile: DockerfilePythonMicroservice
    ports:
      - "8000:8000"  # Пробрасываем порт для отладки
    volumes:
      - ./python-microservice:/app
      - /app/__pycache__  # Игнорируем кэш Python
    environment:
      - PYTHONUNBUFFERED=1
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 10s
    restart: unless-stopped

volumes:
  pgdata_dev: