export {
  analysisResultSlice,
  setPending,
  setPrepareDataGender,
  setPrepareDataAge,
  resetPrepareData,
  sendAnalysisData,
  sendAnalysisResultFile,
  addPointData,
  removePointData,
  clearAllPointData,
  clearRedirect,
  setSelectedPoint,
  removeSelectedPoint,
  resetSelectedPoints,
  SelectAnalysisResultData,
  SelectAnalysisResultDescriptionData,
  SelectAnalysisResultPending,
  SelectAnalysisResultRedirectTo,
  SelectAnalysisResultPrepareDataAge,
  SelectAnalysisResultPrepareDataGender,
  SelectAnalysisResultPointData,
  SelectAnalysisResultError,
  SelectAnalysisResultSelectedList,
  SelectAnalysisResultPrepareDataPointDataByName,
} from "./model";
export type { PointData, ResultDescription, PreparePointData } from "./model";
