export {
  analysisResultSlice,
  setPending,
  setPrepareDataGender,
  setPrepareDataAge,
  resetPrepareData,
  sendAnalysisData,
  addPointData,
  removePointData,
  clearAllPointData,
  clearRedirect,
  SelectAnalysisResultData,
  SelectAnalysisResultDescriptionData,
  SelectAnalysisResultPending,
  SelectAnalysisResultRedirectTo,
  SelectAnalysisResultPrepareDataAge,
  SelectAnalysisResultPrepareDataGender,
  SelectAnalysisResultPointData,
} from "./model";
export type { PointData, ResultDescription, PreparePointData } from "./model";
